/* Заголовки для полей */
export const REPAIR_FIELDS_LABELS = {
  fault_date: "Дата акта осмотра",
  locomotive_model: "Модель локомотива",
  locomotive_number: "Номер локомотива",
  section: "Секция",
  milage: "Пробег",
  fault_discovered: "Выявлено при",
  regional_center: "Региональный центр",
  serial_number: "Зав. номер",
  component_serial_number: "Зав. номер компонента",
  element_serial_number: "Зав. номер элемента",
  manufacture_date: "Дата изготовления",
  quantity: "Кол-во",
  malfunction: "Неисправность",
  note: "Примечание",
  component: "Компонент",
  element: "Элемент",
  new_component: "Установленный компонент",
  new_element: "Установленный элемент",
  repair_type: "Тип ремонта",
  performed_by: "Кем устранялась неисправность",
  equipment_owner: "Владелец оборудования",
  destination: "Демонтированное оборудование подлежит",
  summary: "Краткое содержание",
  status: "Статус",
  supplier: "Поставщик",
  // Поля для ТТН
  ttn_replacement_number: "№ Документа",
  ttn_replacement_date: "Дата получения",
  ttn_from_rc_number: "№ Документа",
  ttn_from_rc_date: "Дата получения",
  ttn_to_supplier_number: "№ Документа",
  ttn_to_supplier_date: "Дата получения",
  ttn_to_supplier_provider: "Перевозчик/Действие",
  ttn_from_supplier_number: "№ Документа",
  ttn_from_supplier_date: "Дата получения",
  ttn_from_supplier_provider: "Перевозчик/Действие",
};

export const BLOCK_TITLES = {
  locomotive_block: "Локомотив и место",
  equipment_block: "Неисправное оборудование",
  repair_block: "Выполненный ремонт",
  status_info: "Статус и ответственность",
  documents: "Рекламационная работа",
  primary_docs: "Первичная документация",
  warranty_notification: "Уведомление",
  warranty_re_notification: "Повторное уведомление",
  warranty_supplier_response: "Ответ поставщика",
  warranty_claim_act_avr: "Рекламационный акт / АВР",
  warranty_research_act: "Акт исследования",
  ttn_replacement: "Документ о замене",
  ttn_from_rc: "Документ об отгрузке с РЦ",
  ttn_to_supplier: "Документ об отгрузке Поставщику",
  ttn_from_supplier: "Документ о возврате от Поставщика",
};
