/* Заголовки для полей */
export const REPAIR_FIELDS_LABELS = {
  fault_date: "Дата акта осмотра",
  locomotive_model: "Модель локомотива",
  locomotive_number: "Номер локомотива",
  section: "Секция",
  milage: "Пробег",
  fault_discovered: "Выявлено при",
  regional_center: "Региональный центр",
  serial_number: "Зав. номер",
  manufacture_date: "Дата изготовления",
  quantity: "Кол-во",
  malfunction: "Неисправность",
  note: "Примечание",
  component: "Компонент",
  element: "Элемент",
  new_component: "Установленный компонент",
  new_element: "Установленный элемент",
  repair_type: "Тип ремонта",
  performed_by: "Кем устранялась неисправность",
  equipment_owner: "Владелец оборудования",
  destination: "Демонтированное оборудование подлежит",
  summary: "Краткое содержание",
  status: "Статус",
  supplier: "Поставщик",
};

export const BLOCK_TITLES = {
  locomotive_block: "Локомотив и место",
  equipment_block: "Неисправное оборудование",
  repair_block: "Выполненный ремонт",
  status_info: "Статус и ответственность",
  documents: "Рекламационная работа",
  primary_docs: "Первичная документация",
  warranty_notification: "Уведомление",
  warranty_re_notification: "Повторное уведомление",
  warranty_supplier_response: "Ответ поставщика",
  warranty_claim_act_avr: "Рекламационный акт / АВР",
};
