export const STOCK_DOCUMENT_TYPES = [
  {
    key: "receipts",
    title: "Приходные ордера",
    description: "Отгрузка оборудования от Поставщиков",
  },
  {
    key: "inplant",
    title: "Внутризаводские накладные",
    description: "Отгрузка оборудования из РЦ на завод",
  },
  {
    key: "outbound",
    title: "Накладные на сторону",
    description: "Отгрузка оборудования Поставщикам",
  },
];

export const STOCK_DOCUMENT_COLUMNS = {
  receipts: [
    { key: "number", title: "Номер" },
    { key: "accompanying_date", title: "Дата сопр. док-та", format: "date" },
    { key: "accompanying_number", title: "Номер сопр. док-та" },
    { key: "supplier", title: "Поставщик" },
    { key: "warehouse", title: "Склад получатель" },
    {
      key: "accounting_date",
      title: "Дата проведения по учёту",
      format: "date",
    },
    { key: "created_at", title: "Создан", format: "datetime" },
    { key: "created_by", title: "Создал" },
    { key: "updated_at", title: "Дата изменения", format: "date" },
    { key: "note", title: "Примечание" },
  ],
  inplant: [
    { key: "document_date", title: "Дата", format: "date" },
    { key: "number", title: "Номер" },
    { key: "status", title: "Статус" },
    { key: "warehouse", title: "Склад отправитель" },
    { key: "issued_by", title: "Выдал" },
    { key: "recipient", title: "Получатель" },
    { key: "accepted_by", title: "Принял работник" },
    { key: "note", title: "Примечание" },
  ],
  outbound: [
    { key: "document_date", title: "Дата", format: "date" },
    { key: "number", title: "Номер" },
    { key: "status", title: "Статус" },
    { key: "warehouse", title: "Склад отправитель" },
    { key: "shipping_date", title: "Дата отгрузки", format: "date" },
    { key: "recipient", title: "Получатель" },
    { key: "created_at", title: "Создан", format: "datetime" },
    { key: "created_by", title: "Создал" },
    { key: "updated_at", title: "Дата изменения", format: "date" },
    { key: "updated_by", title: "Изменил" },
  ],
};

export const STOCK_ITEM_COLUMNS = {
  receipts: [
    { key: "position", title: "№ п/п" },
    { key: "card_number", title: "№ (ном)" },
    { key: "nomenclature", title: "Номенклатура" },
    { key: "document_quantity", title: "Кол-во (док)" },
    { key: "unit", title: "Ед. изм." },
    { key: "nominal_number", title: "Ном. номер" },
    { key: "quantity", title: "Кол-во (факт)" },
    { key: "depot_card", title: "Номера складских карточек" },
    { key: "party_number", title: "Номер партии" },
  ],
  inplant: [
    { key: "nominal_number", title: "Ном. номер" },
    { key: "sender_card", title: "Карточка отправителя" },
    { key: "receiver_card", title: "Карточка получателя" },
    { key: "nomenclature", title: "Обозначение" },
    { key: "quantity", title: "Количество" },
    { key: "unit", title: "Ед. изм." },
    { key: "invoice_number", title: "Номер накладной СУ" },
    { key: "sender_warehouse", title: "Отправитель" },
    { key: "invoice_date", title: "Дата накладной СУ", format: "datetime" },
    { key: "sender_sign", title: "Обозначение отправителя" },
    { key: "item_note", title: "Примечание" },
    { key: "lot_movement_number", title: "Номер движения партии" },
    { key: "parent_lot_movement_number", title: "Родительская партия" },
    { key: "original_document_number", title: "Номер документа партии" },
  ],
  outbound: [
    { key: "card_number", title: "№" },
    { key: "nomenclature", title: "Номенклатура" },
    { key: "nominal_number", title: "Ном. номер" },
    { key: "unit", title: "Ед. изм." },
    { key: "quantity", title: "Количество" },
    { key: "party_number", title: "Партия" },
    { key: "numbered_object", title: "Номерной объект" },
    { key: "origin_document_type", title: "Документ партии" },
    { key: "original_document_number", title: "Номер документа" },
    { key: "origin_document_date", title: "Дата документа", format: "date" },
  ],
};
